version: '3'
services:
  sonarqube:
    image: sonarqube
    ports:
      - "8082:9000"
    networks:
      - sonarnet
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube_db
      - SONAR_JDBC_USERNAME=sonarqube_user
      - SONAR_JDBC_PASSWORD=Admin@2313
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=sonarqube_user
      - POSTGRES_PASSWORD=Admin@2313
      - POSTGRES_DB=sonarqube_db
    networks:
      - sonarnet

networks:
  sonarnet:

